= Vector Spaces =
:doctype: book
:author: Bharath Kumar S P
:email: bharath030195@gmail.com
:stem: latexmath
:eqnums:
:toc:

== What is a Vector Space? ==
We will define a vector space to be a set stem:[V] with an addition stem:[+] and a scalar multiplication stem:[\cdot] on stem:[V].

* An addition on a set stem:[V] is a binary operator that assigns an element stem:[\mathbf{v} + \mathbf{w} \in V] to each pair of elements stem:[\mathbf{v}, \mathbf{w} \in V].
* A scalar multiplication on a set stem:[V] is a unary operator that takes as input an element in stem:[V] and a scalar in the field and gives an element in stem:[V], i.e., it gives an element stem:[\lambda \mathbf{v} \in V] to each stem:[\lambda] in the field and each stem:[\mathbf{v} \in V].

A vector space is a set stem:[V] along with an addition on stem:[V] and a scalar multiplication on stem:[V] such that the following properties hold:

. Commutativity: stem:[\mathbf{v} + \mathbf{w} = \mathbf{w} + \mathbf{v}] for all stem:[\mathbf{v}, \mathbf{w} \in V].
. Associativity: stem:[\mathbf{u} + (\mathbf{v} + \mathbf{w}) = (\mathbf{u} + \mathbf{v}) + \mathbf{w}] and stem:[(ab) \cdot v = a \cdot (b \cdot v)] for all  stem:[\mathbf{u}, \mathbf{v}, \mathbf{w} \in V] and all stem:[a,b] in the field.
. Existence of additive identity: There exists an element stem:[\mathbf{0} \in V] such that stem:[\mathbf{v} + \mathbf{0} = \mathbf{v}] for all stem:[\mathbf{v} \in V].
. Existence of additive inverse: For every stem:[\mathbf{v} \in V], there exists stem:[\mathbf{w} \in V] such that stem:[\mathbf{v} + \mathbf{w} = \mathbf{0}].
. Existence of multiplicative identity: stem:[1 \cdot \mathbf{v} = \mathbf{v}] for all stem:[\mathbf{v} \in V].
. Distributive properties: stem:[a(\mathbf{v} + \mathbf{w}) = a\mathbf{v} + b \mathbf{w}] and stem:[(a+b) \cdot \mathbf{v} = a \cdot \mathbf{v} + b \cdot \mathbf{v}] for all stem:[a,b] in the field and for all stem:[\mathbf{v}, \mathbf{w} \in V].

*Formal Definition:*

Let stem:[V] be a non-empty set. Let stem:[\+, \cdot] be a binary and unary operators defined on stem:[V] (i.e., stem:[V] is closed under stem:[+] and stem:[\cdot]). The triplet stem:[(V, +, \cdot)] is called as a vector space if the above mentioned 8 axioms are satisfied by it. Elements of a vector space are called as vectors.

A vector space over the field stem:[\mathbb{R}] is called a real vector space, i.e, a vector space which considers scalars as real numbers.

Without assuming anything about the nature of stem:[(V, +, \cdot)], we can prove the following from the first principles:

*Property 1:*

Commutativity and associativity for stem:[+] together give stem:[\mathbf{v}_1 + \mathbf{v}_2  + \mathbf{v}_3] for any three vectors. No need to put brackets, addition in any order gives the same result.

[stem]
++++
\begin{align*}
(\mathbf{v}_1 + \mathbf{v}_2) + \mathbf{v}_3 & = \mathbf{v}_1 + (\mathbf{v}_2 + \mathbf{v}_3) && \text{associativity} \\
& = \mathbf{v}_1 + (\mathbf{v}_3 + \mathbf{v}_2) && \text{commutativity} \\
& = (\mathbf{v}_1 + \mathbf{v}_3) + \mathbf{v}_2 && \text{associativity} \\
& \text{so on}
\end{align*}
++++


By induction, we can also make similar statement for stem:[m] vectors and simply write stem:[\mathbf{v}_1 + \mathbf{v}_2  + \dots + \mathbf{v}_m] (any bracketing and ordering is fine).

*Property 2:*
A vector space stem:[V] has a unique additive identity.

Proof: Suppose stem:[\mathbf{0}] and stem:[\mathbf{0}'] are both additive identities for some stem:[V]. Then 

[stem]
++++
\mathbf{0}' = \mathbf{0}' + \mathbf{0} = \mathbf{0} + \mathbf{0}' = \mathbf{0}
++++

We represent the additive identity by symbol stem:[\mathbf{0}].

*Property 3:*
 
Every element in a vectos space stem:[V] has a unique additive inverse.

Proof: Let stem:[\mathbf{v} \in V]. Suppose stem:[\mathbf{w}] and stem:[\mathbf{w}'] are two additive inverses of stem:[\mathbf{v}].

[stem]
++++
\begin{align*}
\mathbf{w} = \mathbf{w} + \mathbf{0} & = \mathbf{w} + (\mathbf{v} + \mathbf{w}') \\
& = (\mathbf{w} + \mathbf{v}) + \mathbf{w}' \\
& = \mathbf{0} + \mathbf{w}' = \mathbf{w}'
\end{align*}
++++

Since we have a unique inverse, we denote the additive inverse of stem:[\mathbf{v}] by symbol stem:[-\mathbf{v}]. When we write stem:[\mathbf{w} - \mathbf{v}], it is nothing but stem:[\mathbf{w} + (- \mathbf{v})].

*Property 4:*

The number 0 times a vector: stem:[0 \cdot \mathbf{v} = \mathbf{0}], which results in the additive identity. This holds for all stem:[\mathbf{v} \in V].

*Property 5:*

A number times the vector stem:[\mathbf{0}]: stem:[\alpha \cdot \mathbf{0} = \mathbf{0}], which results in the additive identity. This holds for all stem:[\alpha \in \mathbb{R}].

*Property 6:* stem:[\alpha \cdot \mathbf{v} = 0 \iff \alpha=0 \text{ or } \mathbf{v}= \mathbf{0}].

*Property 7:*

stem:[-1 \cdot \mathbf{v} = -\mathbf{v}] for all stem:[\mathbf{v} \in V]

Proof: We should prove that stem:[-1 \cdot \mathbf{v}] is the additive inverse of stem:[\mathbf{v}].

[stem]
++++
\begin{align*}
\mathbf{v} + (-1) \cdot \mathbf{v} & = 1 \cdot \mathbf{v} + (-1) \cdot \mathbf{v} \\
& = (1+ (-1)) \cdot \mathbf{v} && \text{distributive property} \\
& = 0\cdot \mathbf{v} = \mathbf{0}
\end{align*}
++++

stem:[(-1) \cdot \mathbf{v}] when added to stem:[\mathbf{v}] gives stem:[\mathbf{0}]. Hence it is the same as the additive inverse.

== Examples of Vector Spaces ==

*Example 01:*

Consider stem:[V] to be a set of all points in stem:[\mathbb{R}^n] (stem:[n] is given). Let stem:[+] be 'usual' vectorial addition. stem:[\cdot] be 'usual' scalar multiplication. Then stem:[\mathbb{V} = (\mathbb{R}^n, + , \cdot)] is a vector space. This space is known as *Euclidean space*.

In this space, a vector means Euclidean vector. The additive identity element is the zero vector, which is denoted by stem:[\mathbf{0}].

This is not the only vector space, we can also define abstract vector spaces.

*Example 02:*

Consider stem:[V] to be a set of all stem:[m \times n] matrices (stem:[m, n] is given). stem:[+] is matrix addition, stem:[\cdot] is 'usual' multiplication of scalar and matrix. Then stem:[(V, + , \cdot)] is a vector space.

In this space, a vector is a matrix. The additive identity element is the zero matrix, which is denoted by stem:[\mathbf{0}].

*Example 03:*

Consider stem:[V] to be a set of all real valued functions on stem:[\mathbb{R}]. stem:[+] is 'usual' sum of functions (point-wise sum) and stem:[\cdot] is 'usual' point-wise scaling.

[stem]
++++
\begin{align*}
& f \in V \implies f(x) \in \mathbb{R} \, \forall x \in \mathbb{R} \\
& g \in V \implies g(x) \in \mathbb{R} \, \forall x \in \mathbb{R} 
\end{align*}
++++

[stem]
++++
\begin{align*}
(f+g)(x) & \equiv f(x) + g(x) \in \mathbb{R} && \forall x \in \mathbb{R} \implies f+g \in V \\
(\alpha \cdot f) (x) & \equiv \alpha f(x) \in \mathbb{R} && \forall x, \alpha \in \mathbb{R} \implies \alpha \cdot f \in V
\end{align*}
++++

Again stem:[(V, + , \cdot)] is a vector space. In the above two definitions, LHS is just notation, RHS is the definition.

In this space, a vector is a function. The additive identity element is the constant zero function, which is denoted by stem:[\mathbf{0}].

*Example 04:*

Consider stem:[V] to be a set of all polynomial functions on stem:[\mathbb{R}]. Call it stem:[V']. it is easy to see that stem:[(V', + , \cdot)] is again a vector space (but is contained in stem:[(V, + , \cdot)] as stem:[V' \subseteq V]).

stem:[V' \subseteq V], where stem:[V'] is the set of all polynomial functions on stem:[\mathbb{R}]. stem:[V] is the set of all real valued functions on stem:[\mathbb{R}].

*Example 05:*

Consider stem:[V] to be a set of all random variables (which are from a defined probability space). Call it stem:[V]. One way of defining the operators is as follows: stem:[+] is 'usual' way to add two random variables, stem:[\cdot] is 'usual' way of scaling a random variable. Again stem:[(V, + , \cdot)] is a vector space.

[stem]
++++
\begin{align*}
(X+Y)(\omega) & \equiv X(\omega) + Y(\omega)  \in \mathbb{R} && \forall \omega \in \Omega \implies X+Y \in V \\
(\alpha \cdot X) (\omega) & \equiv \alpha X(\omega) \in \mathbb{R} && \forall \omega \in \Omega, \alpha \in \mathbb{R} \implies \alpha \cdot X \in V
\end{align*}
++++

The operations stem:[\+] and stem:[\cdot] that we define should satisfy all the 8 axioms stated above. Here the stem:[+] is defined through the stem:[\+] of two real numbers. The scalar addition satisfy all the properties of stem:[+] stated above. And stem:[\cdot] is defined through multiplication of two real numbers, hence it also satisfy all the above properties for stem:[\cdot].

This way addition of two RVs is also a random variable. And scaling a RV is also a random variable. In this space, a vector is a random variable. The additive identity element is a degenerate random variable which takes value 0 with probability 1.

Consider stem:[V'] as the subset of random variables with mean zero. It is easy that stem:[(V', + , \cdot)] is also a vector space.

== Subspaces ==
In many cases, subsets of the entire set of vectors itself formed a vector space. Such vector spaces lying inside other vector spaces are known as sub-spaces.